#include "LightRGBWDrv.h"
#include "stm8s.h"
#include "main.h"


void GPIO_Config()
{
  CLK_PeripheralClockConfig(CLK_PERIPHERAL_TIMER1, ENABLE);


	GPIO_Init(GPIOA,GPIO_PIN_1 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOA,GPIO_PIN_2 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOA,GPIO_PIN_3 , GPIO_MODE_OUT_PP_LOW_FAST);

	GPIO_Init(GPIOC,GPIO_PIN_3 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOC,GPIO_PIN_4 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOC,GPIO_PIN_5 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOC,GPIO_PIN_7 , GPIO_MODE_OUT_PP_LOW_FAST);
	
	GPIO_Init(GPIOD,GPIO_PIN_4 , GPIO_MODE_OUT_PP_LOW_FAST);
	GPIO_Init(GPIOD,GPIO_PIN_6 , GPIO_MODE_OUT_PP_LOW_FAST);

	GPIO_WriteLow(GPIOC,GPIO_PIN_3);
	GPIO_WriteLow(GPIOC,GPIO_PIN_4);
	GPIO_WriteLow(GPIOA,GPIO_PIN_1);
	GPIO_WriteLow(GPIOA,GPIO_PIN_2);
	GPIO_WriteLow(GPIOA,GPIO_PIN_3);
	
	GPIO_WriteHigh(GPIOC,GPIO_PIN_5);
	GPIO_WriteHigh(GPIOC,GPIO_PIN_7);
	GPIO_WriteHigh(GPIOD,GPIO_PIN_4);
	GPIO_WriteHigh(GPIOD,GPIO_PIN_6);



  GPIO_Init(GPIOD,GPIO_PIN_3 , GPIO_MODE_IN_FL_IT);
  EXTI_SetExtIntSensitivity(EXTI_PORT_GPIOD, EXTI_SENSITIVITY_FALL_ONLY);
  EXTI_SetTLISensitivity(EXTI_TLISENSITIVITY_FALL_ONLY);

}

void LED_Pwm_ctrl(uint8_t BValue, uint8_t WValue)
{
  TIM1_SetCompare3(BValue);
  TIM1_SetCompare4(WValue);
  
}

