#include "LightRGBWDrv.h"
#include "stm8s.h"
#include "main.h"


void GPIO_Config_Init()
{
  CLK_PeripheralClockConfig(CLK_PERIPHERAL_TIMER1, ENABLE);


  GPIO_Init(LED1_PORT,LED1_PIN , GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED2_PORT,LED2_PIN , GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(LED3_PORT,LED3_PIN , GPIO_MODE_OUT_PP_LOW_FAST);
  GPIO_Init(OUT_PORT,OUT_PIN , GPIO_MODE_OUT_PP_LOW_FAST);

  GPIO_Init(GPIOD,GPIO_PIN_2 , GPIO_MODE_IN_FL_IT);
  EXTI_SetExtIntSensitivity(EXTI_PORT_GPIOD, EXTI_SENSITIVITY_FALL_ONLY);
  EXTI_SetTLISensitivity(EXTI_TLISENSITIVITY_FALL_ONLY);

}


